### PR TITLE
Docker support changes

### PR DESCRIPTION
**Pull request by dnalborczyk**
https://github.com/dherault/serverless-offline/pull/845

### CODE REVIEW

**Comment by frozenbonito** [comment]
@dnalborczyk Thank you for your PR. I have read it, so let me comment.

I agree that anything docker related be handled within handler runner is the most beautiful way, but I don't think `docker.initialize()` should be called in there.
`docker.initialize()` does following:

- pull base images
- build artifacts
  1. create deploy package (call `sls pakcage`)
https://github.com/frozenbonito/serverless-offline/blob/c114ccc467e1c55fa7aa21ef007b21caf72da4e1/src/docker/artifacts/Artifacts.js#L55-L57
  2. then extract it
https://github.com/frozenbonito/serverless-offline/blob/c114ccc467e1c55fa7aa21ef007b21caf72da4e1/src/docker/artifacts/Artifacts.js#L59-L89

Depending on the serverless config, these tasks can be very time consuming. It would be unacceptable in handler runner.

I think serverless-offline should mimic the actual AWS Lambda.

AWS Lambda probably works as follow when cold-start:

1. create a new container
1. load deploy package into the container
1. extract the package
1. initialize runtime
1. execute global statements outside of handler function
1. run handler function

(When warm-start, it only executes 5.)

On the other hand, serverless-offline must handle follow tasks:

1. pull base image
1. create deploy package (`sls package`)
1. extract the package
1. create and start container with API mode (`docker create` and `docker start`)
1. call invoke API

3 - 5 are equvalent to 3 - 6 in actual Lambda, but 1 and 2 are local invoke specific tasks and they only needs to be executed once.
Therefore, I believe 1 and 2 should be handled outside of handler-runnner.

**Comment by frozenbonito** [comment]
@dnalborczyk I have an idea re-org my PR.
It will remove the docker instance from main, Lamba, LambdaFunctionPool, and LambdaFunction.
May I add some commits my PR?

**Comment by dnalborczyk** [comment]
@frozenbonito  thank you for the explanation!

> but I don't think docker.initialize() should be called in there

yeah, you might be right. I didn't look into the details of `docker.initialize()`.

**Comment by dnalborczyk** [comment]
> @dnalborczyk I have an idea re-org my PR.
> It will remove the docker instance from main, Lamba, LambdaFunctionPool, and LambdaFunction.
> May I add some commits my PR?

absolutely! I just wanted to give you an idea about the organization and structure of the files.

**Comment by frozenbonito** [comment]
@dnalborczyk Thank you! Your idea was very helpful for me.

**Pull request closed without merging**
